#Tested: 2025/01/26
# by Kasper Arfman
name: Build APK
on: [push]
jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Buildozer dependencies
        run: |
          sudo apt update
          sudo apt install openjdk-22-jdk
          sudo apt install python3-pip
          pip3 install --user --upgrade buildozer
          sudo apt update
          sudo apt install -y git zip unzip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev automake build-essential libsqlite3-dev sqlite3 bzip2 libbz2-dev zlib1g-dev libssl-dev openssl libgdbm-dev libgdbm-compat-dev liblzma-dev libreadline-dev libncursesw5-dev uuid-dev
          pip3 install --user --upgrade Cython==0.29.19 virtualenv 
          pip install --user --upgrade buildozer
          echo 'export PATH=$PATH:~/.local/bin/' >> ~/.bashrc

      - name: Handle Java path
        run: |
          export JAVA_HOME=/usr/lib/jvm/java-22-openjdk
          sudo update-java-alternatives -s java-22-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
          yes | buildozer android debug deploy run

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
